# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdf7c30f33114388ff6f40dc7ffa7d9185b9861c6f90a518f92a65c7b08fa58e3efed9b93981d14c279e8226b25c026312dc65db44d7f54c9896bf9873c8654b

test:
  secret_key_base: 9061f1fde528b0509ed9c533bcf32a2c66356ed0fa1d89383245f090d360eaffba484678d96bf25474722cf8e1fd23080ded5dfda001a96ee2e682f60dcdeae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: "<%= ENV["SECRET_KEY_BASE"] %>"
